# Generated by Django 4.2.11 on 2024-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
