# Generated by Django 4.2.11 on 2024-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_product',
            field=models.BooleanField(default=False),
        ),
    ]
