# Generated by Django 4.2.11 on 2024-03-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_food_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionStatus',
        ),
    ]
